#!/usr/bin/env bash
#these work with v2
#place them in your .bash_aliases or maybe .bashrc
#or source this file for single session use
nwal(){
$HOME/.novo-bitcoin/bin/novobitcoin-cli getwalletinfo
}
ninfo(){
$HOME/.novo-bitcoin/bin/novobitcoin-cli getinfo
}
nhelp(){
$HOME/.novo-bitcoin/bin/novobitcoin-cli help
}
nstart(){
$HOME/.novo-bitcoin/bin/nbsv.sh
}
